<?php

namespace Modules\page\models;

use App\Models\Model;
use Illuminate\Support\Facades\Auth;
use Modules\core\models\User;

class Page extends Model
{
    protected $table = 'page';
    protected $primaryKey = 'page_id';
    protected $fillable = ['title', 'description', 'meta_keyword', 'meta_title', 'meta_description', 'created_by', 'slug', 'is_active'];

    public function rules()
    {
        return [
            'title' => 'required|max:255',
            'description' => 'required',
            'slug' => 'nullable|max:255|regex:/^[a-zA-Z0-9_-]+$/i',
            'meta_keyword' => 'nullable|max:255',
            'meta_title' => 'nullable|max:255',
            'meta_description' => 'nullable|max:255',
            'is_active' => 'numeric|min:0|max:1'
        ];
    }

    public function messages()
    {
        return [
            'title' => [
                'required' => ':attribute là bắt buộc'
            ]
        ];
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($model) {
            $model->created_by = Auth::user()->id;
        });
    }

    public function createdBy()
    {
        return $this->hasOne(User::class, 'id', 'created_by');
    }

}
